{
 "title": "UAXSat-PostgresSQL",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "topic": "data" }
   ]
  },
  {
   "title": "CPUTempt",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "topic": "data" }
   ]
  },
  {
   "title": "IMU + GPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT latitude, longitude, altitude, heading_motion FROM grafana_schema.sensor_data"
    }
   ]
  },
  {
   "title": "Press",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 2, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "topic": "data" }
   ]
  },
  {
   "title": "Tempt",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 2, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "topic": "data" }
   ]
  },
  {
   "title": "UV Sensor",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT uva, uvb, uvc FROM grafana_schema.sensor_data "
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "topic": "data" }
   ]
  },
  {
   "title": "Internal Tempt",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "topic": "data" }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "topic": "data" }
   ]
  },
  {
   "title": "GPS Coordinates",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT latitude, longitude FROM grafana_schema.sensor_data "
    }
   ]
  },
  {
   "title": "Temperature sensors",
   "type": "stat",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cpu_temp, uv_temp, temperature FROM grafana_schema.sensor_data "
    }
   ]
  },
  {
   "title": "RAW Data",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, cpu_temp, cpu_usage, ram_usage, latitude, longitude, altitude, heading_motion FROM grafana_schema.sensor_data  "
    }
   ]
  },
  {
   "title": "DATA LOSS",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT cpu_temp, cpu_usage, ram_usage, latitude, longitude, altitude,\r\n                    heading_motion, roll, pitch, heading, acceleration, gyro,\r\n                    magnetic, uva, uvb, uvc, uv_temp, temperature FROM grafana_schema.sensor_data "
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, cpu_temp, cpu_usage, ram_usage, latitude, longitude, altitude,\r\n                    heading_motion, roll, pitch, heading, nmea_sentence, acceleration, gyro,\r\n                    magnetic, uva, uvb, uvc, uv_temp, temperature FROM grafana_schema.sensor_data"
    }
   ]
  }
 ]
}