{
 "title": "UAXSAT IV VISUALIZATION",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Time",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\"           -- Selects the timestamp column, indicating when the sensor readings were recorded\nFROM\n  sensor_readings;      -- Specifies the table that stores the sensor readings\n",
     "topic": "data"
    }
   ]
  },
  {
   "title": "PRESSURE",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  bmp_pressure            -- Selects the pressure value recorded by the BMP sensor\nFROM\n  sensor_readings;        -- Specifies the table that stores the sensor readings\n",
     "topic": "data"
    }
   ]
  },
  {
   "title": "UVA",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  uva AS \"UVA\",              -- Selects the UVA value recorded by the sensor and renames it as \"UVA\"\n  uvb AS \"UVB\",              -- Selects the UVB value recorded by the sensor and renames it as \"UVB\"\n  uvc AS \"UVC\",              -- Selects the UVC value recorded by the sensor and renames it as \"UVC\"\n  \"timestamp\"                -- Selects the timestamp to indicate when these UV readings were recorded\nFROM\n  sensor_readings;           -- Specifies the table that stores the sensor readings\n"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  bmp_temperature AS \"BMP\",        -- Selects the temperature value recorded by the BMP sensor and renames it as \"BMP\"\n  uv_temp AS \"UV\",                 -- Selects the temperature value related to the UV sensor and renames it as \"UV\"\n  dallas_intern AS \"INTERN\",       -- Selects the internal temperature value from the DS18B20 sensor and renames it as \"INTERN\"\n  dallas_extern AS \"EXTERN\",       -- Selects the external temperature value from the DS18B20 sensor and renames it as \"EXTERN\"\n  \"timestamp\"                      -- Selects the timestamp to indicate when these temperature readings were recorded\nFROM\n  sensor_readings;                 -- Specifies the table that stores the sensor readings\n"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "rawSql": "SELECT\n  bmp_pressure,           -- Selects the pressure value recorded by the BMP sensor\n  \"timestamp\"             -- Selects the timestamp to indicate when the pressure reading was recorded\nFROM\n  sensor_readings;        -- Specifies the table that stores the sensor readings\n"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  system_cpu_usage_percent AS \"CPU (%)\",    -- Selects the CPU usage percentage and renames it as \"CPU (%)\"\n  system_ram_usage_percent AS \"RAM (%)\",    -- Selects the RAM usage percentage and renames it as \"RAM (%)\"\n  system_temp_cpu_thermal AS \"CPU (ºC)\"     -- Selects the CPU temperature and renames it as \"CPU (ºC)\"\nFROM\n  sensor_readings;                          -- Specifies the table that stores the sensor readings\n"
    }
   ]
  },
  {
   "title": "UV Sensor",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 6, "x": 12, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  uva AS \"UVA\",              -- Selects the UVA value recorded by the sensor and renames it as \"UVA\"\n  uvb AS \"UVB\",              -- Selects the UVB value recorded by the sensor and renames it as \"UVB\"\n  uvc AS \"UVC\",              -- Selects the UVC value recorded by the sensor and renames it as \"UVC\"\n  \"timestamp\"                -- Selects the timestamp to indicate when these UV readings were recorded\nFROM\n  sensor_readings;           -- Specifies the table that stores the sensor readings\n"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  bmp_temperature AS \"BMP\",        -- Selects the temperature value recorded by the BMP sensor and renames it as \"BMP\"\n  uv_temp AS \"UV\",                 -- Selects the temperature value related to the UV sensor and renames it as \"UV\"\n  dallas_intern AS \"INTERN\",       -- Selects the internal temperature value from the DS18B20 sensor and renames it as \"INTERN\"\n  dallas_extern AS \"EXTERN\",       -- Selects the external temperature value from the DS18B20 sensor and renames it as \"EXTERN\"\n  \"timestamp\"                      -- Selects the timestamp to indicate when these temperature readings were recorded\nFROM\n  sensor_readings;                 -- Specifies the table that stores the sensor readings\n"
    }
   ]
  },
  {
   "title": "Distance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  gps_distance AS \"DISTANCE\"   -- Selects the GPS-calculated distance and renames it as \"Distance\"\nFROM\n  sensor_readings;             -- Specifies the table that stores the sensor readings\n",
     "topic": "data"
    }
   ]
  },
  {
   "title": "Distance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  gps_satellites AS \"SATELLITES\"   -- Selects the number of satellites detected by the GPS and renames it as \"SATELLITES\"\nFROM\n  sensor_readings;                 -- Specifies the table that stores the sensor readings\n",
     "topic": "data"
    }
   ]
  },
  {
   "title": "GPS ACURRACY",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  gps_hdop AS \"HDOP\",       -- Selects the Horizontal Dilution of Precision (HDOP) value from the GPS and renames it as \"HDOP\"\n  gps_vdop AS \"VDOP\",       -- Selects the Vertical Dilution of Precision (VDOP) value from the GPS and renames it as \"VDOP\"\n  gps_pdop AS \"PDOP\",       -- Selects the Position Dilution of Precision (PDOP) value from the GPS and renames it as \"PDOP\"\n  \"timestamp\"               -- Selects the timestamp column to show when these GPS readings were recorded\nFROM\n  sensor_readings;          -- Specifies the table that stores the sensor readings\n",
     "topic": "data"
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  bmp_altitude AS \"BMP\",          -- Selects the altitude value measured by the BMP sensor and renames it as \"BMP\"\n  gps_altitude AS \"GPS\",          -- Selects the altitude value measured by the GPS and renames it as \"GPS\"\n  \"timestamp\",                    -- Selects the timestamp to indicate when these altitude readings were recorded\n  gps_height_geoid AS \"GEOID\"     -- Selects the geoid height value from the GPS and renames it as \"GEOID\"\nFROM\n  sensor_readings;                -- Specifies the table that stores the sensor readings\n"
    }
   ]
  },
  {
   "title": "GPS Coordinates",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  gps_gga_latitude AS \"LATITUDE\",    -- Selects the latitude value from the GPS GGA sentence and renames it as \"LATITUDE\"\n  gps_gga_longitude AS \"LONGITUDE\"   -- Selects the longitude value from the GPS GGA sentence and renames it as \"LONGITUDE\"\nFROM\n  sensor_readings;                   -- Specifies the table that stores the sensor readings\n"
    }
   ]
  },
  {
   "title": "DATA LOSS",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  uva AS \"UV\",                          -- Selects the UVA value recorded by the sensor and renames it as \"UV\"\n  bmp_pressure AS \"BMP\",                -- Selects the pressure value from the BMP sensor and renames it as \"BMP\"\n  acelx AS \"IMU\",                       -- Selects the acceleration value along the X-axis from the IMU sensor and renames it as \"IMU\"\n  dallas_intern AS \"DS18B20\",           -- Selects the internal temperature value from the DS18B20 sensor and renames it as \"DS18B20\"\n  gps_gga_latitude AS \"GPS\",            -- Selects the latitude value from the GPS GGA sentence and renames it as \"GPS\"\n  system_temp_cpu_thermal AS \"SYSTEM\"   -- Selects the CPU temperature from the system sensor and renames it as \"SYSTEM\"\nFROM\n  sensor_readings;                      -- Specifies the table that stores the sensor readings\n"
    }
   ]
  },
  {
   "title": "Velocities",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  gps_speed_mps AS \"Horizontal\",    -- Selects the horizontal speed measured by the GPS (in meters per second) and renames it as \"Horizontal\"\n  bmp_vertical_speed AS \"Vertical\", -- Selects the vertical speed measured by the BMP sensor and renames it as \"Vertical\"\n  \"timestamp\"                       -- Selects the timestamp to indicate when these speed readings were recorded\nFROM\n  sensor_readings;                  -- Specifies the table that stores the sensor readings\n",
     "topic": "data"
    }
   ]
  },
  {
   "title": "ALTITUDE",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  bmp_altitude AS \"BMP\",          -- Selects the altitude value measured by the BMP sensor and renames it as \"BMP\"\n  gps_altitude AS \"GPS\"           -- Selects the altitude value measured by the GPS and renames it as \"GPS\"\nFROM\n  sensor_readings;                -- Specifies the table that stores the sensor readings\n",
     "topic": "data"
    }
   ]
  },
  {
   "title": "RAW DATA",
   "type": "timeseries",
   "gridPos": { "h": 26, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\n    bmp_pressure AS PRESSURE,           -- Selects the pressure value from the BMP sensor and renames it as \"PRESSURE\"\n    bmp_temperature AS BMP_TEMP,        -- Selects the temperature value from the BMP sensor and renames it as \"BMP_TEMP\"\n    bmp_altitude AS BMP_ALT,            -- Selects the altitude value from the BMP sensor and renames it as \"BMP_ALT\"\n    bmp_vertical_speed AS VERTICAL_SPEED, -- Selects the vertical speed measured by the BMP sensor and renames it as \"VERTICAL_SPEED\"\n    dallas_intern AS \"INTERN\",          -- Selects the internal temperature value from the DS18B20 sensor and renames it as \"INTERN\"\n    dallas_extern AS \"EXTERN\",          -- Selects the external temperature value from the DS18B20 sensor and renames it as \"EXTERN\"\n    gps_speed_mps AS SPEED_MPS,         -- Selects the horizontal speed from the GPS in meters per second and renames it as \"SPEED_MPS\"\n    gps_gga_latitude AS LATITUDE,       -- Selects the latitude value from the GPS GGA sentence and renames it as \"LATITUDE\"\n    gps_gga_longitude AS LONGITUDE,     -- Selects the longitude value from the GPS GGA sentence and renames it as \"LONGITUDE\"\n    gps_altitude AS GPS_ALTITUDE,       -- Selects the altitude value from the GPS and renames it as \"GPS_ALTITUDE\"\n    gps_height_geoid AS HEIGHT_GEOID,   -- Selects the height above the geoid from the GPS and renames it as \"HEIGHT_GEOID\"\n    gps_satellites AS SATELLITES,       -- Selects the number of satellites detected by the GPS and renames it as \"SATELLITES\"\n    timestamp                           -- Selects the timestamp to indicate when these readings were recorded\nFROM \n    sensor_readings;                    -- Specifies the table that stores the sensor readings\n"
    }
   ]
  },
  {
   "title": "GPS DATA LOGGER",
   "type": "table",
   "gridPos": { "h": 13, "w": 16, "x": 8, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    gps_gga_latitude AS LATITUDE,    -- Selects the latitude value from the GPS GGA sentence and renames it as \"LATITUDEGGA\"\r\n    gps_gga_longitude AS LONGITUDE,  -- Selects the longitude value from the GPS GGA sentence and renames it as \"LONGITUDEGGA\"\r\n    gps_distance AS DISTANCE,           -- Selects the calculated distance from the GPS and renames it as \"DISTANCE\"\r\n    gps_altitude AS ALTITUDE,           -- Selects the altitude value from the GPS and renames it as \"ALTITUDE\"\r\n    gps_satellites AS SATELLITES,       -- Selects the number of satellites detected by the GPS and renames it as \"SATELLITES\"\r\n    gps_pdop AS PDOP,                   -- Selects the Position Dilution of Precision (PDOP) value from the GPS and renames it as \"PDOP\"\r\n    gps_hdop AS HDOP,                   -- Selects the Horizontal Dilution of Precision (HDOP) value from the GPS and renames it as \"HDOP\"\r\n    gps_vdop AS VDOP,                   -- Selects the Vertical Dilution of Precision (VDOP) value from the GPS and renames it as \"VDOP\"\r\n\r\n    timestamp                           -- Selects the timestamp to indicate when these GPS readings were recorded\r\n\r\nFROM \r\n    sensor_readings;                    -- Specifies the table that stores the sensor readings\r\n"
    }
   ]
  },
  {
   "title": "IMU DATA LOGGER",
   "type": "table",
   "gridPos": { "h": 13, "w": 16, "x": 8, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT \n    acelx AS \"ACELX\",         -- Selects the X-axis acceleration value from the IMU sensor and renames it as \"ACELX\"\n    acely AS \"ACELY\",         -- Selects the Y-axis acceleration value from the IMU sensor and renames it as \"ACELY\"\n    acelz AS \"ACELZ\",         -- Selects the Z-axis acceleration value from the IMU sensor and renames it as \"ACELZ\"\n    girox AS \"GYROX\",         -- Selects the X-axis gyroscope value from the IMU sensor and renames it as \"GYROX\"\n    giroy AS \"GYROY\",         -- Selects the Y-axis gyroscope value from the IMU sensor and renames it as \"GYROY\"\n    giroz AS \"GYROZ\",         -- Selects the Z-axis gyroscope value from the IMU sensor and renames it as \"GYROZ\"\n    magx AS \"MAGX\",           -- Selects the X-axis magnetometer value from the IMU sensor and renames it as \"MAGX\"\n    magy AS \"MAGY\",           -- Selects the Y-axis magnetometer value from the IMU sensor and renames it as \"MAGY\"\n    magz AS \"MAGZ\",           -- Selects the Z-axis magnetometer value from the IMU sensor and renames it as \"MAGZ\"\n    \"timestamp\" AS \"TIME\"     -- Selects the timestamp and renames it as \"TIME\" to indicate when these readings were recorded\nFROM \n    sensor_readings;          -- Specifies the table that stores the sensor readings\n"
    }
   ]
  },
  {
   "title": "GPS Coordinates",
   "type": "geomap",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "rawSql": "SELECT\n  gps_gga_latitude AS \"LATITUDE\",    -- Selects the latitude value from the GPS GGA sentence and renames it as \"LATITUDE\"\n  gps_gga_longitude AS \"LONGITUDE\"   -- Selects the longitude value from the GPS GGA sentence and renames it as \"LONGITUDE\"\nFROM\n  sensor_readings;                   -- Specifies the table that stores the sensor readings\n"
    }
   ]
  }
 ]
}